### ISSUE TITLE
Make sure that all editors play well with Perl 6

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/marketing#10]
# **⚠ Ticket moved to https://github.com/perl6/user-experience/issues/19**

**Comment by cfa** [comment]
@AlexDaniel updated NeoVim to point at the Vim (rather than Emacs) plugin.

**Comment by cfa** [comment]
@AlexDaniel looks like that's an older version (bundled with `vim-perl`).

Perhaps both links can be provided—(i) builtin support, (ii) the more up to date plugin?

**Comment by zoffixznet** [comment]
>  Sublime text | 🤷 unknown

It has a really awful and unusable Perl 6 highligher, so I'd say it's unsupported. I forget where I installed it from, but lack of support in sublime is the only reason I'm using Atom for P6.

**Comment by MasterDuke17** [comment]
I'm pretty sure vim supports Perl 6 by default now.

**Comment by Tyil** [comment]
@MasterDuke17 Perl 6 has decent support by default in vim, but the `vim-perl6` plugin enhances it.

**Comment by AlexDaniel** [comment]
Yeah, I think I fixed that.

**Comment by nxadm** [comment]
Maybe this could be turned into a Wiki page?

**Comment by cfa** [comment]
@nxadm good idea.

We could also potentially snapshot it periodically at https://github.com/perl6/doc so that it's more discoverable for users. Thoughts?

**Comment by AlexDaniel** [comment]
Well, anyone in perl6 github org (≈300 people) should be able to edit the comment, so functionally any comment is like a shitty wiki page (which is often good enough). And that's not the [first time](https://github.com/perl6/doc/issues/711#issuecomment-235414744) we do that. In fact, we probably get more edits here than on the whole [rakudo wiki](https://github.com/rakudo/rakudo/wiki/_history). Also, here you have an option to just write a comment instead of editing.

> that it's more discoverable for users. Thoughts?

This ticket was meant to be a marketing issue… but yes, I see it outgrowing itself a bit.

We already list editor plugins on https://perl6.org/whatever/, maybe we should just extract the *useful* parts from that table.

**Comment by zoffixznet** [comment]
> edit the comment, so functionally any comment is like a shitty wiki page

But that leaves the non-issue Issue open. In the wrong repo too. This stuff has little to do with marketing, but is perfect for our [user-experience repo](https://github.com/perl6/user-experience/issues/).

-----

FWIW, here's a user asking for nano support, if anyone has any advice for them: https://www.reddit.com/r/perl6/comments/881svu/nano_syntax_highlighting_for_perl6/

**Comment by AlexDaniel** [comment]
@zoffixznet you're right! I totally forgot that we had a user-experience repo.

**Comment by zaucker** [comment]
Comma should be added to the list (perhaps not before the beta is started in May 2018).

**Comment by AlexDaniel** [comment]
Sure, once it's out.

**Comment by nxadm** [comment]
A new column may be needed collecting the license information. Something line FOSS/Commercial with Free Usage/Paid License.

C.

**Comment by AlexDaniel** [comment]
OK, added it right away as a plugin for IntelliJ IDEA (I hope that's right). Don't know what to do with Comma as standalone IDE, because this ticket has a different purpose. Maybe we can list it on https://perl6.org/whatever/ once it is out.

**Comment by AlexDaniel** [comment]
Thanks everyone for your comments! This ticked was moved to https://github.com/perl6/user-experience/issues/19.
