### ISSUE TITLE
Server Configuration Issues on HTTP port

### ISSUE THREAD

**Issue by zoffixznet** [perl6/marketing#21]
Ping @moritz since you probably know more about possible cause. 

It used to be that going to [http://marketing.perl6.org/](http://marketing.perl6.org/) redirected you to HTTPS site. No, that leads to just a blank Apache listing.

IIRC there used to be a redirect that redirected everything that isn't a LetsEncrypt verifier to HTTPS

**Comment by moritz** [comment]
@zoffixznet I've fixed it.

The culprit was that there were two `<VirtualHost *:80>` directives for `marketing.perl6.org`, one in the TLS config file (which didn't redirect), one separately (which redirected). I removed the one that didn't redirect.
