### ISSUE TITLE
"say" in example is inappropriate

### ISSUE THREAD

**Issue by ajs** [perl6/marketing#3]
In the example of rounding errors, the text is: "Pick up your favourite language and see what this line of code evaluates to: `say 0.1 + 0.2 == 0.3`. It's not clear what the reader is expected to do, here, since the statement evaluates to a syntax error in nearly every programming language (even Perl 5 withou `-E`).

I would instead recommend:

Pick up your favorite language and print out the result of this arithmetic equality: `0.1 + 0.2 == 0.3`

**Comment by zoffixznet** [comment]
Thanks. Fixed in local sources; will update repo during next update.

![untitled](https://user-images.githubusercontent.com/5747918/32742425-696ba174-c877-11e7-89c3-165e2fbc6320.png)
