### ISSUE TITLE
links in brochure

### ISSUE THREAD

**Issue by llelf** [perl6/marketing#6]
page 17:
1. www.perl6.org/download [http://www.perl6.org/download] → https://perl6.org/downloads
2. there's problem with https://github.com/zoffixznet/r, it breaks on ffi and leads to https://github.com/zof

**Comment by zoffixznet** [comment]
Could you link to the document you're talking about?

I see the problem with the downloads link in [this PDF](https://github.com/perl6/marketing/blob/master/Brochures/Introducing-Perl6-Brochure/Introducing-Perl6-Brochure.pdf), but the zoffixznet/r link isn't a clickable link, so I'm not understanding what you mean by it breaking off.

**Comment by llelf** [comment]
@zoffixznet It is, under Mac OS.
I don't know who to blame exactly (MacOS / InDesign / …). It'd be probably easier to make them all proper links. And change to `https://`.

Because *something* *somewhere* is making them to be links.
But at least it's logical: it breaks because of the ffi ligature. I notice `perl6.party` is not a link for me too  😄 (because .party I presume).

**Comment by zoffixznet** [comment]
Can you try this PDF: https://temp.perl6.party/P-17-Introducing-Perl6-Brochure--PRINT-QUALITY--WITH-BLEED.pdf

Do all the links work OK?

**Comment by llelf** [comment]
👍 all links are fine.
[I'd say skip the `www.`, we are not in the 90s]
