### ISSUE TITLE
“Sigil”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/marketing#8]
This issue is similar to https://github.com/perl6/marketing/issues/7.

> Easy to use
> consistent 
> syntax, using invariable 
> sigils for data-structures

Say you're a C++ or Java developer, would you know what a “sigil” is? The first link in google seems to be [Sigil_(magic)](https://en.wikipedia.org/wiki/Sigil_(magic)), but [Sigil_(computer_programming)](https://en.wikipedia.org/wiki/Sigil_(computer_programming)) is indeed reachable with two clicks through disambiguation.

But OK, then “invariable sigils”? I think this is something only perl5 devs will understand.

**Comment by zoffixznet** [comment]
> But OK, then “invariable sigils”? I think this is something only perl5 devs will understand.

I don't see this as a problem. This information is specifically for people who know what a sigil is. And it's especially useful to have it, since this brochure is very likely to be at the same table as Perl 5 materials.
